
version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: delivery_management
      MYSQL_USER: delivery_user
      MYSQL_PASSWORD: delivery_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: mysql://delivery_user:delivery_password@mysql:3306/delivery_management
    depends_on:
      - mysql
    volumes:
      - ./backend:/app

  frontend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  mysql_data:
